

@host = 192.168.200.131
#@host = 10.200.244.5

@user = admin
@upass = benrocks
@authToken = {{loginA.response.body.token.token}}

###   # get bigip auth token
# @name loginA
POST https://{{host}}/mgmt/shared/authn/login
Content-Type: application/json

{
    "username": "{{user}}",
    "password": "{{upass}}",
    "logonProviderName": "provider"
}

###   # get as3 service info
GET https://{{host}}/mgmt/shared/appsvcs/info
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}


###   # get as3 tasks
GET https://{{host}}/mgmt/shared/appsvcs/task/
#   ?$select=id,results
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}


###   # get as3 declarations
GET https://{{host}}/mgmt/shared/appsvcs/declare/
  # ?$select=id
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}




###   # SEND as3 main sample declaration
# @name decID
POST https://{{host}}/mgmt/shared/appsvcs/declare/
  ?async=true
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}

< ./sample_as3Dec.json



###   # SEND as3 sample 4 declaration
# @name decID
POST https://{{host}}/mgmt/shared/appsvcs/declare/
  ?async=true
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}

< ./sample4_as3Dec.json


###   # SEND as3 sample2vs declaration
# @name decID
POST https://{{host}}/mgmt/shared/appsvcs/declare/
  ?async=true
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}

< ./sample2vs_as3Dec.json


###   # CHECK as3 declaration status
GET https://{{host}}/mgmt/shared/appsvcs/task/{{decID.response.body.id}}
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}


###   # CHECK as3 declaration status
GET https://{{host}}/mgmt/shared/appsvcs/task/797a3a25-22c8-4ab4-a201-dc01c3f48050
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}


###   # get as3 declarations for tenent
# @name decID
GET https://{{host}}/mgmt/shared/appsvcs/declare/Sample_http_06a/
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}


###   # DELETE!!! as3 declaration
# @name decID
DELETE https://{{host}}/mgmt/shared/appsvcs/declare/Sample_01/
  ?async=true
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}

###   # DELETE!!! as3 declaration
# @name decID
GET https://{{host}}/mgmt/shared/appsvcs/task/
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}





###   # get bigip device list
@authToken = {{loginA.response.body.token.token}}
GET https://{{bigip}}/mgmt/shared/resolver/device-groups/cm-bigip-allDevices/devices
  ?$select=hostname,managementAddress,uuid
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}