

@host = 192.168.200.131
@bigiq = 10.200.244.5

@user = admin
@upass = benrocks
@authToken = {{loginA.response.body.token.token}}

###   # get bigip auth token
# @name loginA
POST https://{{host}}/mgmt/shared/authn/login
Content-Type: application/json

{
    "username": "{{user}}",
    "password": "{{upass}}",
    "logonProviderName": "provider"
}

###   # get fast info
GET https://{{host}}/mgmt/shared/fast/info
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}


###   # get f5 host info
GET https://{{host}}/mgmt/shared/identified-devices/config/device-info
  #?$select=hostname,managementAddress,version,product,platformMarketingName
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}


###   # get fast info
GET https://{{host}}/mgmt/shared/
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}



###   # get fast templates
GET https://{{host}}/mgmt/shared/fast/applications
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}


###   # get fast templates
GET https://{{host}}/mgmt/shared/fast/tasks/d81a4ce7-03e5-4c92-8d15-b15cd82b40ba
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}


###   # get fast templates
GET https://{{host}}/mgmt/shared/fast/templates
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}


###   # get fast templates
GET https://{{host}}/mgmt/shared/fast/templatesets
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}







###   # POST fast application
POST https://{{host}}/mgmt/shared/fast/applications
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}

{
  "name": "examples/simple_http",
  "parameters": {
      "tenant_name": "ten3",
      "application_name": "app1",
      "virtual_port": 80,
      "virtual_address": "10.80.0.10",
      "server_port": 80,
      "server_addresses": [
          "10.80.0.21",
          "10.80.0.22"
      ]
  }
}


###   #delete fast applicataion
DELETE https://{{host}}/mgmt/shared/fast/applications/ten3/app1
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}





###   # get bigip device list
@authToken = {{loginA.response.body.token.token}}
GET https://{{bigiq}}/mgmt/shared/resolver/device-groups/cm-bigip-allDevices/devices
  ?$select=hostname,managementAddress,uuid
Content-Type: application/json
X-F5-Auth-Token: {{authToken}}




###   get list of files/directories in directory
GET https://api.github.com/repos/F5Networks/f5-telemetry-streaming/contents/examples/



###   get list of files in directory
GET https://api.github.com/repos/F5Networks/f5-telemetry-streaming/contents/examples/declarations
  ?$select=name,url


###   get details of github file
GET https://api.github.com/repos/F5Networks/f5-telemetry-streaming/contents/examples/declarations/action_matching.json



###  Get raw content of github file
GET https://raw.githubusercontent.com/F5Networks/f5-telemetry-streaming/master/examples/declarations/action_matching.json




