



###
GET https://api.github.com/repos/F5Networks/f5-telemetry-streaming/releases










async function getTSexamples(){
	return await callHTTPS({
		method: 'GET',
		host: 'api.github.com',
		path: '/repos/F5Networks/f5-telemetry-streaming/contents/examples/declarations',
		headers: {
			'Content-Type': 'application/json',
			'User-Agent': 'F5 VScode FAST extension'
		}
	});
}